#!/bin/bash

# Name of the workspace
workspace_name="🎶"

# Check whether workspace exists
workspace_exists=$(swaymsg -t get_workspaces | jq -e ".[] | select(.name == \"$workspace_name\")")

if [ -z "$workspace_exists" ]; then
    # If workspace does not exist, create it
    swaymsg workspace $workspace_name
    swaymsg exec "firefox --new-window 'https://open.spotify.com'"
else 
    swaymsg workspace $workspace_name
fi
