[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--config", "~/.config/dprint/dprint.json", "--stdin", "md"]}
language-servers = [{name = "marksman"}]
