#!/usr/bin/env python3

DICTIONARY = {
    "a": "Alfa",
    "b": "Bravo",
    "c": "Charlie",
    "d": "Delta",
    "e": "Echo",
    "f": "Foxtrot",
    "g": "Golf",
    "h": "Hotel",
    "i": "India",
    "j": "Juliett",
    "k": "Kilo",
    "l": "Lima",
    "m": "Mike",
    "n": "November",
    "o": "Oscar",
    "p": "Papa",
    "q": "Quebec",
    "r": "Romeo",
    "s": "Sierra",
    "t": "Tango",
    "u": "Uniform",
    "v": "Victor",
    "w": "Whiskey",
    "x": "X-ray",
    "y": "Yankee",
    "z": "Zulu",
    "1": "One",
    "2": "Two",
    "3": "Three",
    "4": "Four",
    "5": "Five",
    "6": "Six",
    "7": "Seven",
    "8": "Eight",
    "9": "Nine",
    "0": "Zero",
}

import sys

def main():
    if len(sys.argv[1:]) == 0:
        for key, val in DICTIONARY.items():
            print(val)
    else:
        # Join all arguments into a single string, split into words
        for word in sys.argv[1:]:
            output = []
            for char in word:
                output.append(DICTIONARY.get(char.lower(), char))
            print(" ".join(output))

if __name__ == "__main__":
    main()
